[general]
import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml",
    "~/.config/alacritty/keybindings.toml"
]
[window]

#opacity = 0.9
padding.x = 2 
padding.y = 2

decorations = "Full"
decorations_theme_variant = "None"
dynamic_padding = true


[font]
size = 16
normal = { family = "Fira Code", style = "Regular" }
#normal = { family = "3270 Nerd Font Mono", style = "Mono"}
offset.x = 0 
offset.y = 0 


[selection]
save_to_clipboard = true

[cursor]
unfocused_hollow = true


